---
# tasks file for configure-and-init-kubeadm

- name: Ensure the kubernetes dir exists
  file:
    path: "{{ config_dir }}"
    state: directory
    mode: '0755'

- name: Create kubeadm config file
  copy:
    dest: "{{ config_dir }}/kubeadm-config.conf"
    content: |
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: ClusterConfiguration
      kubernetesVersion: v1.30.2
      networking:
        serviceSubnet: "10.96.0.0/16"
        podSubnet: "10.244.0.0/24"
      controlPlaneEndpoint: "192.168.56.30:6443"
      apiServer:
        certSANs:
        - "192.168.56.30"
        extraArgs:
          advertise-address: "192.168.56.30"
      etcd:
        local:
          extraArgs:
            listen-peer-urls: "https://192.168.56.30:2380"
            listen-client-urls: "https://192.168.56.30:2379"
            advertise-client-urls: "https://192.168.56.30:2379"
            initial-advertise-peer-urls: "https://192.168.56.30:2380"
      ---
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: InitConfiguration
      localAPIEndpoint:
        advertiseAddress: "192.168.56.30"
        bindPort: 6443
      nodeRegistration:
        criSocket: unix:///run/containerd/containerd.sock

- name: Check if kubeadm is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_initialized

- name: Initialize Kubernetes cluster with kubeadm and save output to a file
  shell: kubeadm init --config /etc/kubernetes/kubeadm-config.conf | tee /home/ansible/bin/kubeadm-init-output-{{ ansible_date_time.iso8601 | regex_replace("[^a-zA-Z0-9]", "-") }}.log
  register: kubeadm_init_output
  when: not kubeadm_initialized.stat.exists

