---
- name: Prepare to install Kubeadm
  hosts: k8snodes
  become: yes
  roles:
    - disable_selinux

    # - install_container_runtime_containerd
    - download_and_install_containerd_binaries
    - configure_containerd
    - install_runc_for_containerd
    - install_cni_plugins_for_containerd

    - enable_ipv4_packet_forwarding
    - open_k8s_ports
    - install_k8s_repo
    - install_k8s_components
    - disable_swap
    - configure_and_start_kubelet

- name: Install Kubeadm
  hosts: kmaster
  become: yes
  roles:
    - configure_and_init_kubeadm
