apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: httpd-24
  name: httpd-24
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: httpd-24
  type: NodePort
status:
  loadBalancer: {}
