apiVersion: v1
data:
  GOOGLE_API_KEY: VjA1aGVsUjVSRzR0U2preWNYb3RVV0ozWDNGTldHWlZkbFY0Y2t0dlR6WmZNbVJ5T0U5bENnPT0=
  SECRET_KEY: UlZkQlluaHJjbU0wWHpZSw==
kind: Secret
metadata:
  creationTimestamp: null
  name: solargeometry
