apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: solargeometry
  name: solargeometry
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solargeometry
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: solargeometry
    spec:
      containers:
      - image: igwegbu/solargeometry:latest
        name: solargeometry
        ports:
        - containerPort: 5004
        resources: {}
        envFrom:
        - secretRef:
            name: solargeometry
status: {}
