---
# tasks file for install-cni-plugins-for-containerd
- name: Ensure the /opt/cni/bin directory exists
  file:
    path: "{{ dest_dir }}"
    state: directory
    mode: '0755'
  notify: Restart containerd

- name: Download the archive tarball and extract it
  unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v1.5.1/cni-plugins-linux-amd64-v1.5.1.tgz
    dest: "{{ dest_dir }}"
    mode: '0755'
    remote_src: yes
  notify: Restart containerd
